### ISSUE TITLE
Set up simple SSG Markdown blog

### ISSUE THREAD

**Issue by mdroidian** [DiscourseGraph/discourse-graph#20]
Takes a folder of markdown blog posts and generates static site on compile.

Users only have to checkout a PR, upload a markdown file into the proper , and merge the 

Markdown can contain specific YAML:
Title, Description, Hero Image, etc

https://nextjs.org/docs/pages/building-your-application/configuring/mdx
https://vercel.com/templates/next.js/blog-starter-kit

**Comment by sid597** [comment]
Michael is this a separate project from the website or do have to integrate it into the website?

**Comment by mdroidian** [comment]
This will be integrated into the nextjs website.  

We can use `apps/website/app/blog` to start for the blog landing page.
We would add a new section to the homepage showing the first 3 blog posts by date.

**Comment by mdroidian** [comment]
We could also see if the amount of work is the same as doing https://www.sanity.io/.
Intuitively I think it might be similar.

**Comment by sid597** [comment]
We can't use sanity with react 19, so either we have to downgrade react or not use sanity, its your call @mdroidian. Meanwhile I will try to setup the blog using nextjs and vercel. 

https://www.sanity.io/help/react-19
https://arewereact19yet.sanity.build/

**Comment by mdroidian** [comment]
Alright, lets see if the dependencies for using SSG/Markdown are compatible with React 19 and go from there. 👍
